### PR TITLE
Represent missing shares as nil internally

### LINKED ISSUE #71: Revert #66
#66 was based on the wrong assumption that the flattened data square slice given to `RepairExtendedDataSquare` _is not modified in place while it is_. In fact, the given slice is modified in place, and library users can and should access the repaired shares through it, so the change to make the `eds` accessible on `ErrByzantineRow/Col` is not needed anymore.

### PR DESCRIPTION
**Pull request by adlerjohn**
Fixes #71 #72

1. Bump Go version to 1.17
2. Fixes #71, reverting the changes made in #66 ([579abb7](https://github.com/celestiaorg/rsmt2d/pull/76/commits/579abb71c03178ac384944f5c49310185699eee1))
3. Remove bit matrix and instead simply keep `nil` shares as `nil`.
4. General cleanup and modernization (e.g. using range-based `for`s).
5. **Important**: fixed a bug where orthogonal cols/rows were never actually checked for correctness ([323f8fa](https://github.com/celestiaorg/rsmt2d/pull/76/commits/323f8fae6ad0a0208979a9f3d06b9ea27c564593)). Prior to this change, the condition to perform the check was essentially "if a share is missing and the col/row is complete" which is obviously never true; a col/row with a missing share is never complete. Fixing this exposed that the _rebuilt_ row/col was being used rather than the orthogonal col/row.

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
Did a first pass and this looks very good to me! 🙌🏼  Before I approve I'll do a more thorough 2nd pass (soon).

File: extendeddatacrossword.go [hunk 1]
```diff
@@ -415,10 +359,39 @@ func noMissingData(input [][]byte) bool {
 	return true
 }
 
+func numOnes(input [][]byte) int {
```
Comment (liamsi) [inline extendeddatacrossword.go:362]: Is this function used anywhere? If not, is there a reason to add it? Looks like we should delete it.

File: extendeddatacrossword.go [hunk 2]
```diff
@@ -415,10 +359,39 @@ func noMissingData(input [][]byte) bool {
...
+	var counter int
+	for _, d := range input {
+		if d != nil {
+			counter++
+		}
+	}
+
+	return counter
+}
+
```
Comment (liamsi) [inline extendeddatacrossword.go:372]:
```suggestion
```

File: extendeddatacrossword.go (hunk 1 above)
Comment (adlerjohn) [reply extendeddatacrossword.go:362]: Ah shoot I ported the bitmatrix functions over than forgot to remove that now-unused now 😂

File: infectiousRSGF8.go [hunk 3]
```diff
@@ -19,10 +19,11 @@ func NewRSGF8Codec() *rsGF8Codec {
 	return &rsGF8Codec{make(map[int]*infectious.FEC)}
 }
 
-// Encode uses uses the infectous RSGF8 codec to encode the provided data
 func (c *rsGF8Codec) Encode(data [][]byte) ([][]byte, error) {
```
Comment (evan-forbes) [inline infectiousRSGF8.go:22]: why are we removing this comment?

File: rsmt2d_test.go [hunk 4]
```diff
@@ -68,7 +67,84 @@ func TestEdsRepairRoundtripSimple(t *testing.T) {
...
+			err = rsmt2d.RepairExtendedDataSquare(
+				eds.RowRoots(),
+				eds.ColRoots(),
+				flattened,
+				tt.codec,
+				rsmt2d.NewDefaultTree,
+			)
+			if err != nil {
+				// Should now passing, since sufficient data.
+				t.Errorf("RepairExtendedDataSquare failed")
```
Comment (liamsi) [inline rsmt2d_test.go:145]:
```suggestion
				t.Errorf("RepairExtendedDataSquare failed: %v", err)
```

File: rsmt2d_test.go [hunk 5]
```diff
@@ -68,7 +67,84 @@ func TestEdsRepairRoundtripSimple(t *testing.T) {
...
+			err = rsmt2d.RepairExtendedDataSquare(
+				eds.RowRoots(),
+				eds.ColRoots(),
+				flattened,
+				tt.codec,
+				rsmt2d.NewDefaultTree,
+			)
+			if err == nil {
+				// Should fail since insufficient data.
+				t.Errorf("RepairExtendedDataSquare did not fail")
```
Comment (liamsi) [inline rsmt2d_test.go:131]: nit: It would be even nicer if the test would communicate which error you are expecting here (if feasible).

**Review by liamsi — APPROVED** [review]
Awesome work 👏🏼

**Review by evan-forbes — APPROVED** [review]
wow, this is a great improvement! only one minor nit

File: infectiousRSGF8.go (hunk 3 above)
Comment (adlerjohn) [reply infectiousRSGF8.go:22]: I added doctrings to the interface rather than the implementation.

File: rsmt2d_test.go (hunk 5 above)
Comment (adlerjohn) [reply rsmt2d_test.go]: Fixed in [6f587bc](https://github.com/celestiaorg/rsmt2d/pull/76/commits/6f587bc54aedbd39e7a2255707f2f6dcbd9e43a6)

File: rsmt2d_test.go [hunk 6]
```diff
@@ -66,9 +65,86 @@ func TestEdsRepairRoundtripSimple(t *testing.T) {
...
+			err = rsmt2d.RepairExtendedDataSquare(
+				eds.RowRoots(),
+				eds.ColRoots(),
+				flattened,
+				tt.codec,
+				rsmt2d.NewDefaultTree,
+			)
+			if err == nil {
+				// Should fail since insufficient data.
+				t.Errorf("RepairExtendedDataSquare did not fail. Expected ErrUnrepairableDataSquare but got nil.")
```
Comment (liamsi) [inline rsmt2d_test.go:131]: Optional: Better use the error directly instead of hard coding the string here. Also, we could assert that via errors.Is or errors.As.

Comment (liamsi) [reply rsmt2d_test.go:131]: Or simply:
```suggestion
				t.Errorf("RepairExtendedDataSquare did not fail. Expected %v but got nil.", ErrUnrepairableDataSquare)
```

Comment (adlerjohn) [reply rsmt2d_test.go]: Fixed in [5ffe833](https://github.com/celestiaorg/rsmt2d/pull/76/commits/5ffe83307d9ca2ca8af297160e42de27d89d28b9)

**Review by liamsi — APPROVED** [review]
(Still) excellent work :)
